// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsSbuaUA9d8fRY1DtcCD4sthiemW_WgOo',
    appId: '1:160137972718:android:55f53a30b5dd804b0f5cff',
    messagingSenderId: '160137972718',
    projectId: 'jumblebook-327a0',
    databaseURL: 'https://jumblebook-327a0.firebaseio.com',
    storageBucket: 'jumblebook-327a0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCclI-Jqq0-WwR1SfEU0r1JUNtVnF6bYSY',
    appId: '1:160137972718:ios:8ce8007cca52aa750f5cff',
    messagingSenderId: '160137972718',
    projectId: 'jumblebook-327a0',
    databaseURL: 'https://jumblebook-327a0.firebaseio.com',
    storageBucket: 'jumblebook-327a0.firebasestorage.app',
    iosClientId:
        '160137972718-s0lr9okp7lai6e6k723tk5ndromb8r5o.apps.googleusercontent.com',
    iosBundleId: 'xyz.bsquared.jumblebook',
  );
}
