name: Simple iOS TestFlight Deployment

on:
  push:
    branches: [main]
  workflow_dispatch:
    inputs:
      version_bump:
        description: 'Version bump type (patch/minor/major)'
        required: false
        default: 'patch'

jobs:
  build-and-deploy:
    runs-on: macos-12
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.0'

      - name: Install dependencies
        run: flutter pub get

      - name: Create Firebase configuration file
        env:
          GOOGLE_SERVICE_INFORMATION_PLIST: ${{ secrets.GOOGLE_SERVICE_INFORMATION_PLIST }}
        run: |
          echo "$GOOGLE_SERVICE_INFORMATION_PLIST" | base64 --decode > ios/Runner/GoogleService-Info.plist
          echo "Created GoogleService-Info.plist"

      - name: Build iOS app
        run: flutter build ios --release --no-codesign

      - name: Set up keychain
        run: |
          KEYCHAIN_PATH=$RUNNER_TEMP/app-signing.keychain-db
          KEYCHAIN_PASSWORD=temporary
          security create-keychain -p "$KEYCHAIN_PASSWORD" "$KEYCHAIN_PATH"
          security set-keychain-settings -lut 21600 "$KEYCHAIN_PATH"
          security unlock-keychain -p "$KEYCHAIN_PASSWORD" "$KEYCHAIN_PATH"

      - name: Import distribution certificate
        env:
          IOS_DISTRIBUTION_CERTIFICATE_BASE64: ${{ secrets.IOS_DISTRIBUTION_CERTIFICATE_BASE64 }}
          IOS_CERTIFICATE_PASSWORD: ${{ secrets.IOS_CERTIFICATE_PASSWORD }}
        run: |
          echo "$IOS_DISTRIBUTION_CERTIFICATE_BASE64" | base64 --decode > distribution.p12
          security import distribution.p12 -k "$KEYCHAIN_PATH" -P "$IOS_CERTIFICATE_PASSWORD" -A -t cert -f pkcs12
          rm distribution.p12

      - name: Import provisioning profile
        env:
          IOS_PROFILE_BASE64: ${{ secrets.IOS_PROFILE_BASE64 }}
        run: |
          echo "$IOS_PROFILE_BASE64" | base64 --decode > profile.mobileprovision
          mkdir -p "$HOME/Library/MobileDevice/Provisioning Profiles"
          mv profile.mobileprovision "$HOME/Library/MobileDevice/Provisioning Profiles/"
          sudo chown -R "$USER:staff" "$HOME/Library/MobileDevice/Provisioning Profiles/"

      - name: Archive the app
        env:
          APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
        run: |
          cd ios
          xcodebuild -workspace Runner.xcworkspace \
            -scheme Runner \
            -configuration Release \
            -archivePath build/Runner.xcarchive \
            -destination 'generic/platform=iOS' \
            DEVELOPMENT_TEAM="$APPLE_TEAM_ID" \
            -allowProvisioningUpdates \
            clean archive

      - name: Create exportOptions.plist
        env:
          APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
        run: |
          cat > ios/build/options.plist << EOF
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
              <key>method</key>
              <string>app-store</string>
              <key>teamID</key>
              <string>$APPLE_TEAM_ID</string>
              <key>signingStyle</key>
              <string>automatic</string>
          </dict>
          </plist>
          EOF

      - name: Export IPA
        run: |
          cd ios
          xcodebuild -exportArchive \
            -archivePath build/Runner.xcarchive \
            -exportPath build \
            -exportOptionsPlist build/options.plist \
            -allowProvisioningUpdates

      - name: Set up App Store Connect API key
        env:
          APPLE_API_PRIVATE_KEY: ${{ secrets.APPLE_API_PRIVATE_KEY }}
        run: |
          mkdir -p "$HOME/.appstoreconnect/private_keys"
          echo "$APPLE_API_PRIVATE_KEY" > "$HOME/.appstoreconnect/private_keys/AuthKey_${{ secrets.APPLE_API_KEY }}.p8"

      - name: Upload to TestFlight
        env:
          APPLE_API_KEY: ${{ secrets.APPLE_API_KEY }}
          APPLE_API_KEY_ISSUER_ID: ${{ secrets.APPLE_API_KEY_ISSUER_ID }}
        run: |
          IPA_PATH="ios/build/Runner.ipa"
          xcrun altool --upload-app \
            -f "$IPA_PATH" \
            --type ios \
            --apiKey "$APPLE_API_KEY" \
            --apiIssuer "$APPLE_API_KEY_ISSUER_ID" \
            --verbose